<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.545" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-06-12T04:46:53" tests="0" file="cypress/e2e/api_usuarios.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="API Tests Users" timestamp="2025-06-12T04:46:53" tests="1" time="0.524" failures="1">
    <testcase name="API Tests Users Realizar Login no Sistema" time="0.000" classname="Realizar Login no Sistema">
      <failure message="`cy.request()` failed on:

https://serverest.dev/login

The response we received from your web server was:

  &gt; 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://serverest.dev/login
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.4.1 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;content-length&quot;: 48
}
Body: {&quot;email&quot;:&quot;teste11@gmail.com&quot;,&quot;password&quot;:&quot;teste&quot;}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  &quot;access-control-allow-origin&quot;: &quot;*&quot;,
  &quot;x-dns-prefetch-control&quot;: &quot;off&quot;,
  &quot;x-frame-options&quot;: &quot;SAMEORIGIN&quot;,
  &quot;strict-transport-security&quot;: &quot;max-age=15552000; includeSubDomains&quot;,
  &quot;x-download-options&quot;: &quot;noopen&quot;,
  &quot;x-content-type-options&quot;: &quot;nosniff&quot;,
  &quot;x-xss-protection&quot;: &quot;1; mode=block&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=utf-8&quot;,
  &quot;x-cloud-trace-context&quot;: &quot;76d1cee0a5ed3f881b7c355baaddbde9&quot;,
  &quot;date&quot;: &quot;Thu, 12 Jun 2025 04:46:53 GMT&quot;,
  &quot;server&quot;: &quot;Google Frontend&quot;,
  &quot;content-length&quot;: &quot;48&quot;
}
Body: {
  &quot;message&quot;: &quot;Email e/ou senha inválidos&quot;
}


https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://serverest.dev/login

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://serverest.dev/login
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/14.4.1 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 48
}
Body: {"email":"teste11@gmail.com","password":"teste"}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  "access-control-allow-origin": "*",
  "x-dns-prefetch-control": "off",
  "x-frame-options": "SAMEORIGIN",
  "strict-transport-security": "max-age=15552000; includeSubDomains",
  "x-download-options": "noopen",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "content-type": "application/json; charset=utf-8",
  "x-cloud-trace-context": "76d1cee0a5ed3f881b7c355baaddbde9",
  "date": "Thu, 12 Jun 2025 04:46:53 GMT",
  "server": "Google Frontend",
  "content-length": "48"
}
Body: {
  "message": "Email e/ou senha inválidos"
}


https://on.cypress.io/request
    at <unknown> (http://localhost:39897/__cypress/runner/cypress_runner.js:136322:72)
    at tryCatcher (http://localhost:39897/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:39897/__cypress/runner/cypress_runner.js:1489:31)
    at Promise._settlePromise (http://localhost:39897/__cypress/runner/cypress_runner.js:1546:18)
    at Promise._settlePromise0 (http://localhost:39897/__cypress/runner/cypress_runner.js:1591:10)
    at Promise._settlePromises (http://localhost:39897/__cypress/runner/cypress_runner.js:1671:18)
    at _drainQueueStep (http://localhost:39897/__cypress/runner/cypress_runner.js:2377:12)
    at _drainQueue (http://localhost:39897/__cypress/runner/cypress_runner.js:2370:9)
    at Async._drainQueues (http://localhost:39897/__cypress/runner/cypress_runner.js:2386:5)
    at Async.drainQueues (http://localhost:39897/__cypress/runner/cypress_runner.js:2256:14)
From Your Spec Code:
    at Context.ee (webpack://automacaotestesapicypress/./node_modules/cypress-plugin-api/dist/support.js:14:2002)
    at wrapped (http://localhost:39897/__cypress/runner/cypress_runner.js:141516:43)]]></failure>
    </testcase>
  </testsuite>
</testsuites>